export const HookInlineFormStrings = {
  autoSavePending: "AutoSave Pending, please check for errors...",
  savePending: "Save Pending, please check for errors...",
  remaining: "remaining",
  saving: "Saving...",
  seeLess: "See less",
  expand: "Expand",
  required: "Required",
  save: "Save",
  cancel: "Cancel",
  create: "Create",
  update: "Update",
  na: "N/A",
  saveError: "Error saving form",
  errorBoundary: {
    title: "Something went wrong and the form crashed...",
    please: "Please",
    icm: "open an ICM ticket",
    andInclude: "and include a screenshot of this page",
  },
  confirm: "Confirm",
  linkTitleLabel: "Link Title",
  linkUrlLabel: "Link URL",
  add: "Add",
  edit: "Edit",
  deleteLabel: "Delete",
  remove: "Remove",
  unknown: "Unknown",
  noServicesSelected: "No Service Selected",
  close: "Close",
  loading: "Loading",
  noResultsFound: "No results found",
  suggestedPeople: "Suggested People",
  suggestedContacts: "Suggested contacts",
  clickToClear: "Click here to Clear",
  clear: "Clear",
  addServicesLabel: "Add Services",
  editServicesLabel: "Edit Services",
  urlRequired: "Invalid Url (http/https required)",
  openExpandedTextEditor: "Open Expanded Editor",
  closeExpandedTextEditor: "Close Expanded Editor",
  unsavedChanges: "Unsaved Changes",
  returnToEditing: "Return to Editing",
  dontSave: "Don't save",
  overview: "Overview",
  saveChangesTo: (title: string) => {
    return `Do you want to save your changes to ${title}?`;
  },
  by: "by",
  dataCenterRegionsPlaceholder: "Select Region(s)",
  editPlaybookPanelTitle: "Edit Playbook",
  pasteUrl: "To add an ADO work item, paste its entire url here",
  msxView: {
    linkText: "MSX View",
  },
};
